version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2.102-sdk
    steps:
      - run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
      - run: apt-get install git-lfs
      - checkout
      - run: pwd
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --no-build Oxbind.Test
      - run: dotnet ~/.nuget/packages/reportgenerator/4.0.5/tools/netcoreapp2.0/ReportGenerator.dll --reports:Oxbind.Test/coverage.opencover.xml --targetdir:Coverlet-html
      - store_artifacts:
          path: /root/project/Coverlet-html
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
